# Generated by Django 4.2.27 on 2026-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_enable_postgres_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSensyIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_base_url', models.CharField(blank=True, help_text='Public site URL, no trailing slash (e.g. https://crm.example.com). Used to show webhook URL.', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret used to validate signature headers from AiSensy (preferred auth mode).', max_length=255)),
                ('webhook_token', models.CharField(blank=True, help_text='Fallback token validation if signature secret is not used.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='When disabled, incoming AiSensy events are ignored.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AiSensy integration',
                'verbose_name_plural': 'AiSensy integration',
            },
        ),
    ]
