# Generated by Django 4.2.27 on 2026-05-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_lead_status_choices_awaiting_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='can_create_own_leads',
        ),
    ]
